# Generated by Django 5.2.5 on 2025-08-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
