# Generated by Django 5.2.5 on 2025-08-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0002_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
