# Generated by Django 5.2.5 on 2025-08-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0005_remove_cartitem_description_remove_products_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
