# Generated by Django 5.2.5 on 2025-09-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0007_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='linkImg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
