# Generated by Django 5.2.5 on 2025-09-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0008_category_linkimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='linkImg',
            new_name='imageLink',
        ),
    ]
