# Generated by Django 5.2.5 on 2025-09-04 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0009_rename_linkimg_category_imagelink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
