# Generated by Django 5.2.5 on 2025-09-04 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0010_rename_name_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='imageLink',
            new_name='imageUrl',
        ),
    ]
