# Generated by Django 5.2.5 on 2025-09-04 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0011_rename_imagelink_category_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
