# Generated by Django 5.2.5 on 2025-09-04 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0012_remove_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='imageUrl',
        ),
    ]
