# Generated by Django 5.2.5 on 2025-09-05 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0013_rename_image_product_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='name',
        ),
    ]
