# Generated by Django 5.2.5 on 2025-09-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0015_remove_cartitem_cart_remove_cartitem_product_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
