# Generated by Django 5.2.5 on 2025-09-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0016_payment_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
