# Generated by Django 5.2.5 on 2025-09-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0017_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productImages/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
