# Generated by Django 5.2.5 on 2025-09-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0018_product_image_alter_product_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('food', 'Food'), ('fashion', 'Fashion'), ('electronics', 'Electronics'), ('health', 'Health'), ('furniture', 'Furniture')], max_length=50),
        ),
    ]
