# Generated by Django 5.2.5 on 2025-09-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0019_shop_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categoryImages/'),
        ),
    ]
