# Generated by Django 5.2.5 on 2025-09-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0020_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=255),
        ),
    ]
