# Generated by Django 5.2.5 on 2025-09-29 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0022_product_created_at_product_shop_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
