# Generated by Django 5.2.5 on 2025-09-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0023_shop_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_name',
            new_name='name',
        ),
    ]
