# Generated by Django 5.2.5 on 2025-09-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0024_rename_shop_name_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storeImages/'),
        ),
    ]
