# Generated by Django 5.2.5 on 2025-09-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0026_remove_shop_image_shop_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(default='storeLogos/default-imgzz', upload_to='storeLogos/'),
        ),
    ]
