# Generated by Django 5.2.5 on 2025-09-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0028_alter_shop_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Basmati rice garnished with vegetables, pepper and some diced meat in the same'),
        ),
    ]
