# Generated by Django 5.2.5 on 2025-09-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0029_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
