# Generated by Django 5.2.5 on 2025-09-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0030_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
