# Generated by Django 5.2.5 on 2025-09-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0031_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='productImages/'),
        ),
    ]
