# Generated by Django 5.2.5 on 2025-09-29 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0032_alter_product_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to='productApi.category'),
        ),
    ]
