# Generated by Django 5.2.5 on 2025-09-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0034_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
