# Generated by Django 5.2.5 on 2025-09-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0035_alter_product_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productImages/'),
        ),
    ]
