# Generated by Django 5.2.5 on 2025-10-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0038_product_user_shop_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shop',
            new_name='shop_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='user',
            new_name='user_id',
        ),
    ]
