# Generated by Django 5.2.5 on 2025-10-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0039_rename_user_payment_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shop_id',
            new_name='shop',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='user_id',
            new_name='user',
        ),
    ]
